[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "qtile-window-trashbin"
authors = [{name = "Paul Hoffmann", email = "phfn@phfn.de"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://phfn.de"
